name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    uses: ./.github/workflows/_quality.yml

  test:
    uses: ./.github/workflows/_test.yml


